- alias: 'Turn on outdoor lights when away at sunset'
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: group.all_devices
      state: not_home
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_lights

- alias: 'Turn on outdoor lights at sunset'
  trigger:
    - platform: sun
      event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.outdoor_lights

- alias: 'Turn off outdoor lights at sunrise'
  trigger:
    - platform: sun
      event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: group.outdoor_lights

- alias: 'Turn off all lights when away'
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: 'Turn on living room lights when home in the evening'
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
    - platform: state
      entity_id: group.all_devices
      to: 'home'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.living_room

- alias: 'Push notification when freezer temperature too high'
  trigger:
    platform: numeric_state
    entity_id: sensor.freezer_temperature
    above: 0
    for:
      minutes: 15
  action:
    service: notify.mobile_app_pixel_3
    data_template:
      title: "Freezer temperature warning"
      message: "{{ states.sensor.freezer_temperature.state }}°F"

- alias: 'Turn on grow lights in the morning'
  trigger:
    platform: time
    at: "3:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.grow_lights

- alias: 'Turn off grow lights at night'
  trigger:
    platform: time
    at: "21:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.grow_lights
