esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

logger:

api:

ota:

switch:
  - id: ${devicename}_relay
    platform: gpio
    internal: true
    pin: D1

binary_sensor:
- id: ${devicename}_sensor
  platform: gpio
  internal: true
  pin:
    number: D2
    mode: INPUT_PULLUP
    inverted: False
  device_class: garage_door
  filters:
    - delayed_on_off: 20ms

cover:
  - platform: template
    name: ${friendlyname}
    lambda: |-
      if (id(${devicename}_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: ${devicename}_relay
      - delay: 1s
      - switch.turn_off: ${devicename}_relay
    close_action:
      - switch.turn_on: ${devicename}_relay
      - delay: 1s
      - switch.turn_off: ${devicename}_relay
    stop_action:
      - switch.turn_on: ${devicename}_relay
      - delay: 1s
      - switch.turn_off: ${devicename}_relay
